[package]
name = "gamemstr-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custom_derive = "0.1.7"
diesel = { version = "2.0.3", features = ["postgres"] }
gamemstr-common = "0.1.0"
r2d2 = "0.8.10"
r2d2-diesel = "1.0.0"
rocket = "0.4.11"
rocket_codegen = "0.4.11"
serde = { version = "1.0.155", features = ["derive"] }
serde_derive = "1.0.155"
serde_json = "1.0.94"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json"]