CREATE TABLE creatures (
    id                      VARCHAR PRIMARY KEY,
    name                    VARCHAR NOT NULL,
    creature_type           JSONB NOT NULL,
    alignment               JSONB NOT NULL,
    armor_class             INT NOT NULL,
    health_points           JSONB NOT NULL,
    speed                   JSONB NOT NULL,
    stats                   JSONB NOT NULL,
    saving_throws           JSONB,
    damage_resistances      JSONB,
    damage_immunities       JSONB,
    damage_vulnerabilities  JSONB,
    condition_immunities    JSONB,
    skills                  JSONB,
    senses                  JSONB,
    languages               JSONB,
    challenge_rating        JSONB NOT NULL,
    racial_traits           JSONB,
    description             VARCHAR,
    actions                 JSONB,
    lair                    JSONB,
    others                  JSONB
);