name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install latest rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
    - name: Clean
      run: cargo clean
    - name: Build
      run: cargo build --verbose
  test:
  
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: 1234
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432
    
    steps:
    - name: Checkout latest commit
      uses: actions/checkout@v3
    - name: Install latest rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
    - name: Clean
      run: cargo clean
    - name: Diesel Migrations
      run: cp .env.example .env && cargo install diesel_cli --no-default-features -F postgres && diesel migration run
    - name: Run tests
      run: cargo test --verbose
